import plotly.graph_objects as go
from plotly.offline import plot

from pymongo import MongoClient

client = MongoClient('mongodb://localhost:27017/')
db = client['proyectp']
collection = db['restaurantes']

data = collection.find({}, {'nombre': 1, 'mesas': 1})

nombres = []
nro_mesas = []

for d in data:
    nombres.append(d['nombre'])
    nro_mesas.append(d['mesas'])

fig = go.Figure(data=[go.Bar(x=nombres, y=nro_mesas)])

html_content = plot(fig, include_plotlyjs=False, output_type='div')
blade_content = f"{{-- Generated by Python --}}\n\n{html_content}"
with open('grafico_barras.blade.php', 'w') as file:
    file.write(blade_content)
